name: Analyze Logs with AI Agent

on:
  workflow_run:
    workflows: ["python-tests"]  # This refers to the first workflow
    types:
      - completed  # Triggered when the first workflow completes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  analyze_logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Install jq
      run: |
        sudo apt-get install jq -y

    - name: Fetch logs from previous workflow run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching logs from the previous run..."
        # Fetch the ID of the most recent workflow run for the "python-tests" workflow
        run_id=$(gh api "repos/${{ github.repository }}/actions/runs?workflow_id=python-tests&status=completed&per_page=1" \
          | jq -r '.workflow_runs[0].id')
        
        # Fetch the logs URL from GitHub API
        logs_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/logs"
        
        # Download the logs as a zip file
        curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $logs_url --output logs.zip
        
        # Unzip the logs file
        unzip logs.zip -d logs || { echo "Failed to unzip logs"; exit 1; }
        
        # Combine all the logs into one file
        cat logs/**/*.txt > combined_logs.txt

    - name: Process logs and send to AI agent
      run: |
        echo "Sending logs to AI agent for analysis..."
        
        # Call your AI agent and pass the combined logs file as input
        python tools/dylan_ai_agent.py < combined_logs.txt > ai-analysis-result.txt
        
        # Output the AI analysis results
        echo "AI analysis completed. Results:"
        cat ai-analysis-result.txt