name: Python Tests

on:
  workflow_dispatch:
    inputs:
      sample_github_workflows_branch:
        description: "Branch of sample_github_workflows"
        required: false
        default: "main"
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.sample_github_workflows_branch }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        set -e
        python -m unittest discover -s tests > result.log 2>&1
        cat result.log

    - name: Analyze logs with AI Agent
      if: failure()
      run: |
        cd "${GITHUB_WORKSPACE}/tools"
        python dylan_ai_agent.py < "${GITHUB_WORKSPACE}/result.log" > "${GITHUB_WORKSPACE}/ai-analysis-result.txt"
        cat "${GITHUB_WORKSPACE}/ai-analysis-result.txt"
