name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest

    - name: Run tests
      run: |
        set -e
        python -m unittest discover -s tests > result.log 2>&1 || true
        cat result.log

    - name: Analyze logs with AI Agent
      if: failure()
      run: |
        python tools/dylan_ai_agent.py < result.log > ai-analysis-result.txt
        cat ai-analysis-result.txt
