name: Python Tests

on:
  workflow_dispatch:
    inputs:
      sample_github_workflows_branch:
        description: "Branch of sample_github_workflows"
        required: false
        default: "main"
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.sample_github_workflows_branch }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        set -e
        python -m unittest discover -s tests

    - name: Analyze logs with AI Agent
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching logs from GitHub Actions API..."
        run_id=$(echo $GITHUB_RUN_ID)
        logs_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/logs"
        curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $logs_url --output logs.zip
        unzip logs.zip -d logs
        cat logs/*.txt > combined_logs.txt
        python tools/dylan_ai_agent.py < combined_logs.txt > ai-analysis-result.txt
        cat ai-analysis-result.txt
